"""Executable macro explanations for groups of semantic transformation concepts."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Mapping


class TransformationExplanationEngine:
    """Compress micro-concepts into executable transformation explanations."""

    system_name = "transformation_explanation_engine"

    EXPLANATION_RULES = [
        {
            "explanation_id": "gravity_simulation_with_collision",
            "required_any": {"gravity", "gravity_simulation"},
            "supporting": {
                "falling",
                "support",
                "collision",
                "rest_state",
                "downward_motion",
                "component_merging",
                "connectivity_change",
                "topology_change",
            },
            "macro_concept": "gravity_simulation",
            "summary": (
                "Unsupported objects fall downward until support or collision; "
                "contact may merge components and the final state settles at rest."
            ),
            "theory_families": ("physics", "topology", "spatial"),
            "mechanism_families": ("gravity",),
            "canonical_operations": ("translate", "connect_components"),
            "constraints": ("down_axis_required", "support_stops_motion", "topology_update_optional"),
        },
        {
            "explanation_id": "symmetric_object_creation",
            "required_any": {"object_creation", "density_increase", "symmetry_creation"},
            "supporting": {
                "object_creation",
                "density_increase",
                "symmetry_creation",
                "symmetry_break",
                "relative_position",
                "spatial_relation",
                "topology_change",
                "transformation_sequence",
            },
            "macro_concept": "symmetric_object_creation",
            "summary": (
                "The output is generated by creating a symmetric duplicate or expansion "
                "of the source object while preserving local color and spatial structure."
            ),
            "theory_families": ("density", "spatial", "topology", "compound"),
            "mechanism_families": ("object_creation", "density"),
            "canonical_operations": ("duplicate", "expand", "mirror_horizontal", "mirror_vertical"),
            "constraints": ("preserve_local_color", "symmetry_axis_required", "relative_position_required"),
        },
        {
            "explanation_id": "symbolic_color_remapping",
            "required_any": {"symbolic_remapping", "color_mapping"},
            "supporting": {
                "symbolic_remapping",
                "color_mapping",
                "object_identity_preservation",
                "shape_preservation",
                "transformation_sequence",
            },
            "macro_concept": "symbolic_color_remapping",
            "summary": (
                "Symbols or color classes are remapped consistently while preserving "
                "object shape and spatial placement."
            ),
            "theory_families": ("color", "compound"),
            "mechanism_families": ("color_mapping",),
            "canonical_operations": ("recolor",),
            "constraints": ("mapping_must_be_consistent", "preserve_shape", "preserve_position"),
        },
        {
            "explanation_id": "quantity_rule_transformation",
            "required_any": {"object_counting", "cardinality", "quantity_transformation"},
            "supporting": {
                "object_counting",
                "cardinality",
                "quantity_preservation",
                "quantity_transformation",
                "numerical_reasoning",
                "set_reasoning",
            },
            "macro_concept": "quantity_rule_transformation",
            "summary": (
                "Objects are grouped into a count domain, cardinality is extracted, "
                "and a quantity rule determines preservation, creation, or removal."
            ),
            "theory_families": ("quantity",),
            "mechanism_families": ("object_counting",),
            "canonical_operations": ("duplicate", "remove_object", "select_object"),
            "constraints": ("grouping_rule_required", "count_domain_required"),
        },
        {
            "explanation_id": "rotation_or_reflection",
            "required_any": {"rotation", "reflection", "rotation_reflection", "orientation_change"},
            "supporting": {
                "rotation",
                "reflection",
                "rotation_reflection",
                "orientation_change",
                "spatial_relation",
                "relative_position",
            },
            "macro_concept": "rotation_reflection",
            "summary": (
                "The object or grid changes orientation through a rotation or reflection "
                "while preserving color and topology."
            ),
            "theory_families": ("spatial",),
            "mechanism_families": ("rotation",),
            "canonical_operations": ("rotate", "mirror_horizontal", "mirror_vertical"),
            "constraints": ("reference_frame_required", "preserve_colors"),
        },
    ]

    def explain(
        self,
        concepts: list[str] | None = None,
        runtime_context: Mapping[str, Any] | None = None,
        transformation_language_report: Mapping[str, Any] | None = None,
    ) -> dict[str, Any]:
        runtime_context = runtime_context if isinstance(runtime_context, Mapping) else {}
        concepts = list(dict.fromkeys(str(item) for item in concepts or []))
        language = (
            transformation_language_report
            if isinstance(transformation_language_report, Mapping)
            else {}
        )
        concept_set = set(concepts)
        explanations = [
            self._build_explanation(rule, concept_set)
            for rule in self.EXPLANATION_RULES
            if concept_set.intersection(rule["required_any"])
        ]
        explanations = [
            item for item in explanations
            if item["supporting_concept_count"] > 0
        ]
        explanations.sort(
            key=lambda item: (
                item["explanation_confidence"],
                item["supporting_concept_count"],
            ),
            reverse=True,
        )
        primary_statement = language.get("primary_statement")
        if isinstance(primary_statement, Mapping):
            for explanation in explanations:
                if self._statement_matches_explanation(
                    primary_statement,
                    explanation,
                ):
                    explanation["statement_id"] = primary_statement.get("statement_id")
                    explanation["transformation_statement"] = dict(primary_statement)
                    explanation["explanation_confidence"] = round(
                        min(explanation["explanation_confidence"] + 0.08, 1.0),
                        4,
                    )
            explanations.sort(
                key=lambda item: (
                    item["explanation_confidence"],
                    item["supporting_concept_count"],
                ),
                reverse=True,
            )
        selected = explanations[0] if explanations else None
        return {
            "system": self.system_name,
            "TRANSFORMATION_EXPLANATION_REPORT": True,
            "input_concepts": concepts,
            "transformation_language_report": language,
            "explanation_count": len(explanations),
            "candidate_explanations": explanations,
            "selected_explanation": selected,
            "macro_concept": selected.get("macro_concept") if selected else None,
            "primary_statement": primary_statement,
            "executable_explanation": bool(selected),
            "micro_concepts_compressed": len(concepts),
            "compression_ratio": round(
                (1.0 / max(len(concepts), 1)) if selected else 0.0,
                4,
            ),
            "timestamp": str(datetime.utcnow()),
        }

    def _build_explanation(self, rule, concept_set):
        matched = sorted(concept_set.intersection(rule["supporting"]))
        support_ratio = len(matched) / max(len(rule["supporting"]), 1)
        required_hit = bool(concept_set.intersection(rule["required_any"]))
        confidence = min(1.0, 0.45 + support_ratio * 0.45 + (0.10 if required_hit else 0.0))
        return {
            "explanation_id": rule["explanation_id"],
            "macro_concept": rule["macro_concept"],
            "summary": rule["summary"],
            "statement_id": None,
            "supporting_concepts": matched,
            "supporting_concept_count": len(matched),
            "theory_families": list(rule["theory_families"]),
            "mechanism_families": list(rule["mechanism_families"]),
            "canonical_operations": list(rule["canonical_operations"]),
            "constraints": list(rule["constraints"]),
            "explanation_confidence": round(confidence, 4),
            "executable": bool(rule["canonical_operations"]),
        }

    def _statement_matches_explanation(self, statement, explanation):
        statement_id = statement.get("statement_id")
        explanation_id = explanation.get("explanation_id")
        return (
            statement_id == "gravity_motion_statement"
            and explanation_id == "gravity_simulation_with_collision"
        ) or (
            statement_id == "symmetric_creation_statement"
            and explanation_id == "symmetric_object_creation"
        ) or (
            statement_id == "symbolic_color_statement"
            and explanation_id == "symbolic_color_remapping"
        ) or (
            statement_id == "quantity_statement"
            and explanation_id == "quantity_rule_transformation"
        ) or (
            statement_id == "orientation_statement"
            and explanation_id == "rotation_or_reflection"
        )


transformation_explanation_engine = TransformationExplanationEngine()


__all__ = [
    "TransformationExplanationEngine",
    "transformation_explanation_engine",
]
